Add network config descriptions
citahub/citahub-docs pull request #259
Opened 2019-05-18 14:27 UTC by leeyr338

Add network config descriptions

2019-05-18 15:17 UTC, kaikai1024 commented on docs/cita/operation/service-config.md
> +* `max_connects` : 配置本节点的最大连接数。本节点到达最大连接数时，将拒绝连接其它节点。如果不设置，该配置项默认为 `666`。
100 or 666?

2019-05-18 15:36 UTC, boundless-forest requested changes

2019-05-18 15:36 UTC, ouwenkg commented on docs/cita/operation/service-config.md
默认值，和上边示例对应起来比较好吧

2019-05-19 09:34 UTC, leeyr338 commented on docs/cita/operation/service-config.md
> +* `max_connects` : 配置本节点的最大连接数。本节点到达最大连接数时，将拒绝连接其它节点。如果不设置，该配置项默认为 `666`。
666, 如果这个配置项不设置。`CITA` 会默认为 666。

2019-05-19 09:42 UTC, leeyr338 commented on docs/cita/operation/service-config.md
这里默认值指的是 `CITA` 系统默认的，指的是当配置文件中没有这项时的默认值。
它与 `create` 脚本生成 toml 的值还不太一样。

2019-05-20 02:26 UTC, ouwenkg commented on docs/cita/operation/service-config.md
> +* `max_connects` : 配置本节点的最大连接数。本节点到达最大连接数时，将拒绝连接其它节点。如果不设置，该配置项默认为 `666`。
`max_connects = 100` , 那这个地方的默认最大值是 100, 和这里的 666, 有关系吗?

2019-05-20 03:10 UTC, leeyr338 commented on docs/cita/operation/service-config.md
> +* `max_connects` : 配置本节点的最大连接数。本节点到达最大连接数时，将拒绝连接其它节点。如果不设置，该配置项默认为 `666`。
没有关系。
这个 `toml`  文件表达的不是 sample 吗？只是一个示例而矣；
我这里说的默认值指的是当这个配置系不置时，`CITA` 系统默认的值：

```toml
pub const DEFAULT_MAX_CONNECTS: usize = 666;
...
let max_connects = cfg.max_connects.unwrap_or(DEFAULT_MAX_CONNECTS);
```

2019-05-20 06:14 UTC, kaikai1024 commented on docs/cita/operation/service-config.md
> +* `max_connects` : 配置本节点的最大连接数。本节点到达最大连接数时，将拒绝连接其它节点。如果不设置，该配置项默认为 `666`。
明白了。
这里除了 network ，其他配置文件都是从 config_tool 下面的 config_example 下面拷贝过来的，也就是 example 下面的其实是默认配置，可能需要改个名字，不过这是另外一个问题了。

2019-05-20 06:15 UTC, kaikai1024 commented on docs/cita/operation/service-config.md
> +* `max_connects` : 配置本节点的最大连接数。本节点到达最大连接数时，将拒绝连接其它节点。如果不设置，该配置项默认为 `666`。
后面可能需要把不是生成的也就是你新添加的这几个都其他模块类似，在 config_example 下添加一个 toml 文件。代码里的 default 写在配置文件里，我觉得比较好

2019-05-20 06:18 UTC, kaikai1024 approved these changes

2019-05-20 06:20 UTC, kaikai1024 commented
TODO: Use the `config_example` link to maintain one info.

2019-05-20 07:03 UTC, leeyr338 commented on docs/cita/operation/service-config.md
> +* `max_connects` : 配置本节点的最大连接数。本节点到达最大连接数时，将拒绝连接其它节点。如果不设置，该配置项默认为 `666`。
> 代码里的 default 写在配置文件里，我觉得比较好
这个 CITA 系统的默认值，我觉得在以 CITA 内部控制比较好；
default 写在配置文件里，仅是 `create` 时生成配置文件的 default 值，不应该与 CITA 的 default 值混在一起。
如果用户在升级上来的时候，没有用 `create` 生成新的配置文件，就比较难控制了，而实际场景可能往往也会是这样。

2019-05-20 07:06 UTC, kaikai1024 commented on docs/cita/operation/service-config.md
> +* `max_connects` : 配置本节点的最大连接数。本节点到达最大连接数时，将拒绝连接其它节点。如果不设置，该配置项默认为 `666`。
> 配置文件的 default 值，不应该与 CITA 的 default 值混在一起。

怎么区分这两个呢？ 现在其他模块的 toml 配置里好像有一堆的默认值

2019-05-21 02:16 UTC, ouwenkg commented on docs/cita/operation/service-config.md
> +* `max_connects` : 配置本节点的最大连接数。本节点到达最大连接数时，将拒绝连接其它节点。如果不设置，该配置项默认为 `666`。
> 其他配置文件都是从 config_tool 下面的 config_example 下面拷贝过来的，也就是 example 下面的其实是默认配置

这一块还是有点不太理解, network.toml 这个配置文件应该是在起节点的过程中自动生成的, 在这个生成过程中写入的配置, 难道不应该是系统运行时的默认配置吗?  cita network 在运行时的默认最大链接数是 666, 然后文档里仅仅因为是个 example 就写成 100? 那可以改成 200 之类的吗?

2019-05-21 02:52 UTC, leeyr338 commented on docs/cita/operation/service-config.md
> +* `max_connects` : 配置本节点的最大连接数。本节点到达最大连接数时，将拒绝连接其它节点。如果不设置，该配置项默认为 `666`。
当然可以。

先描述一个场景，假如有用户在 v0.22.0 以前配置了一条链，然后上了生产环境。
现在需要升级到 v0.24.0 ， 而 max_connects 是新加的配置项；用户在大概率的选择是直接使用原有链的配置，而不是用新的配置工具重新生成链的配置。

这个时候 CITA 系统只能使用上文我所描述的 `666` 这个默认值。

而你所描述的 `network.toml` 中的默认值是 `create` 脚本的默认值；而对于 `CITA` 这个软件来说，它就不是默认值了。

总结：
我们所说的默认值所针对的 *表达对象* 是不一样的。

而我认为，当我们描述 `CITA` 软件的默认值时，应以其内部的默认值为准！

2019-05-21 03:05 UTC, ouwenkg commented on docs/cita/operation/service-config.md
> +* `max_connects` : 配置本节点的最大连接数。本节点到达最大连接数时，将拒绝连接其它节点。如果不设置，该配置项默认为 `666`。
OK

2019-05-21 03:05 UTC, boundless-forest approved these changes

2019-05-21 03:18 UTC, merged