update github from cryptape to citahub
citahub/citahub-docs pull request #413
Opened 2020-01-19 08:23 UTC by QingYanL

update github from cryptape to citahub

2020-01-19 09:13 UTC, rainchen approved these changes

2020-01-20 03:59 UTC, leeyr338 approved these changes

2020-01-20 04:02 UTC, rainchen requested changes
DONT touch files within website/, they were auto generated by tools

2020-01-20 04:05 UTC, rink1969 commented
这个pr不改吧。
website下面都是生成的文件。
pr中涉及的修改，在最新的版本源码里面已经改了。

历史版本我们就不要动了，保持原样即可。
我看有些修改，比如 getMetaData 的结果里的链接。
改了之后反而不符合历史版本的情况了。

2020-01-20 04:05 UTC, closed without merging