fix faq store transaction description
citahub/citahub-docs pull request #415
Opened 2020-02-06 05:04 UTC by QingYanL

fix faq store transaction description

2020-02-06 08:49 UTC, boundless-forest requested changes

2020-02-06 08:49 UTC, ouwenkg commented on docs/cita/faq.md
得到存证内容！

2020-02-07 01:04 UTC, leeyr338 commented on docs/cita/faq.md
中文与英文间有空隔。

2020-02-07 06:37 UTC, rink1969 commented on docs/cita/faq.md
建议这样：
存证是向存证指令地址发交易，要存证的内容放在交易的data字段。读取是根据存证交易哈希调用 getTransaction ，然后将结果中的 content 反序列化，得到交易的信息，其中的 data 字段即为存证内容。详见[存证操作说明]。

2020-02-07 07:59 UTC, rink1969 approved these changes

2020-02-07 08:03 UTC, boundless-forest approved these changes

2020-02-07 08:16 UTC, merged