update url to relative paths
citahub/citahub-docs pull request #429
Opened 2020-03-02 04:00 UTC by QingYanL

[cherry-pick] update url to relative paths

2020-03-02 11:40 UTC, rink1969 commented on docs/cita/economics/charge.md
> +* 也可以采用类似挖矿奖励的方式分发。CITA 采用了[系统自动执行合约]的机制，可以实现每区块自动执行一个代币分发合约，向相关节点分发奖励。运营方可以在创世块创建足够多的系统代币，锁定到一个激励合约，并在激励合约中编写按照选举合约结果分发出块奖励的命令。
这样改了之后就没链接了吧？

2020-03-02 11:42 UTC, rink1969 commented on docs/cita/economics/charge.md
> +* 也可以采用类似挖矿奖励的方式分发。CITA 采用了[系统自动执行合约]的机制，可以实现每区块自动执行一个代币分发合约，向相关节点分发奖励。运营方可以在创世块创建足够多的系统代币，锁定到一个激励合约，并在激励合约中编写按照选举合约结果分发出块奖励的命令。
方括弧两边没有空格

2020-03-02 11:42 UTC, rink1969 commented on docs/cita/faq.md
> +详见 [初始化配置后生成的目录结构]
后面没有句号

2020-03-02 11:43 UTC, rink1969 commented on docs/cita/faq.md
> +在 v0.23.0 及以后版本，如果打开了 --enable_version 配置，可以通过 JSON-RPC 接口 getVersion 获取，详细见[rpc getversion]。其他版本需要通过运行 binary 文件方式, 运行 cita-jsonrpc --version 查看。
方括弧两边没有空格

2020-03-02 12:15 UTC, QingYanL commented on docs/cita/economics/charge.md
> +* 也可以采用类似挖矿奖励的方式分发。CITA 采用了[系统自动执行合约]的机制，可以实现每区块自动执行一个代币分发合约，向相关节点分发奖励。运营方可以在创世块创建足够多的系统代币，锁定到一个激励合约，并在激励合约中编写按照选举合约结果分发出块奖励的命令。
已全部更新

2020-03-03 04:55 UTC, rink1969 submitted a review, later dismissed

2020-03-03 04:56 UTC, rink1969 commented
冲突了，需要解决一下冲突

2020-03-03 06:59 UTC, QingYanL commented
> 冲突了，需要解决一下冲突

已解决

2020-03-03 07:27 UTC, rink1969 approved these changes

2020-03-04 01:48 UTC, rainchen approved these changes

2020-03-04 01:52 UTC, jerry-yu requested changes
我记得当时是有个格式要求，英文后面空一格

2020-03-04 01:59 UTC, jerry-yu approved these changes

2020-03-04 02:01 UTC, merged