add run cita-cli instructions
citahub/citahub-docs pull request #455
Opened 2020-08-04 08:11 UTC by QingYanL

add run cita-cli instructions

2020-08-05 03:04 UTC, rink1969 submitted a review, later dismissed

2020-08-12 04:04 UTC, rainchen commented on docs/cita/getting-started/run-cli.md
> +> * "address"：帐号地址
不是`帐号` ， 是`账户`账户`！必需严格统一术语，参考词汇表：https://docs.citahub.com/zh-CN/cita/glossary

2020-08-12 04:05 UTC, rainchen commented on docs/cita/getting-started/run-cli.md
> +```shell
一对 ``` 的前后要空一行

2020-08-12 04:05 UTC, rainchen requested changes
please fix

2020-08-12 06:11 UTC, UDLD approved these changes

2020-08-12 06:11 UTC, UDLD approved these changes

2020-08-12 06:11 UTC, UDLD submitted a review, later dismissed

2020-08-14 07:01 UTC, QingYanL commented
> please fix

@rainchen  已修复

2020-08-14 11:01 UTC, rainchen approved these changes

2020-08-17 11:07 UTC, xiangmeiLu approved these changes

2020-08-18 02:08 UTC, merged