format style for java sdk
citahub/citahub-docs pull request #461
Opened 2020-09-25 02:20 UTC by QingYanL

format style for java sdk

2020-09-25 02:25 UTC, rainchen commented on docs/toolchain/sdk/cita-java-sdk.md
> +$ java -jar build/libs/cita-sdk-20.2.0.jar solidity generate tests/src/main/resources/Token.bin tests/src/main/resources/Token.abi -o tests/src/main/java/ -p com.citahub.cita.tests`
you missed the trailing `

2020-09-25 02:26 UTC, rainchen requested changes
use correct markdown

2020-11-04 07:34 UTC, rainchen commented on docs/toolchain/sdk/cita-java-sdk.md
> +$ java -jar build/libs/cita-sdk-20.2.0.jar solidity generate tests/src/main/resources/Token.bin tests/src/main/resources/Token.abi -o tests/src/main/java/ -p com.citahub.cita.tests`
@QingYanL please fix

2020-11-04 09:54 UTC, xiangmeiLu submitted a review, later dismissed

2020-11-09 03:04 UTC, UDLD approved these changes

2020-11-09 05:50 UTC, rainchen approved these changes

2020-11-09 06:18 UTC, merged