The link - up section of the document has been updated
citahub/citahub-docs pull request #47
Opened 2019-02-22 09:08 UTC by wangfh666

Fixed a note about initializing the chain in the automatic execution contract。

2019-02-22 09:09 UTC, wangfh666 commented
@kaikai1024   Please review the

2019-02-22 16:27 UTC, kaikai1024 requested changes

2019-02-22 16:27 UTC, kaikai1024 commented on docs/cita/system/auto-exec.md
> -*首先需要启动一条链，具体方法见快速入门部分*
not in this.

check the https://github.com/cryptape/citahub-docs/issues/46

2019-02-22 16:33 UTC, kaikai1024 commented
And the title.

2019-02-24 15:19 UTC, kaikai1024 commented
@ouwenkg You can help to do it.

2019-02-25 07:55 UTC, kaikai1024 approved these changes

2019-02-25 08:00 UTC, ouwenkg commented
Need to update docs in the following directory? @kaikai1024 
https://github.com/cryptape/citahub-docs/blob/master/website/translated_docs/zh-CN/version-0.20.2/cita/configuration/chain-configuration.md

2019-02-25 08:00 UTC, kaikai1024 requested changes

2019-02-25 08:00 UTC, kaikai1024 commented on docs/cita/system/auto-exec.md
> +启动链接下来的步骤见[快速搭链](../getting-started)部分。
快速搭链 -> 快速入门

2019-02-25 08:02 UTC, kaikai1024 commented
> Need to update docs in the following directory? @kaikai1024
> https://github.com/cryptape/citahub-docs/blob/master/website/translated_docs/zh-CN/version-0.20.2/cita/configuration/chain-configuration.md

@Keith-CY

2019-02-25 08:54 UTC, kaikai1024 approved these changes

2019-02-25 10:01 UTC, merged